blank_issues_enabled: false
contact_links:
  - name: ğŸ™‹ğŸ¾ğŸ™‹ğŸ¼â€Question
    url: https://discord.gg/s9xNnaEY
    about: Feel free to ask your question by sending a message on the questions channel.
